# Generated by Django 4.2.2 on 2023-06-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_project_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
